apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-demo
  name: web-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-demo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-demo
    spec:
      containers:
      - image: muhammadluthfias/web-demo:18
        name: web-demo
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: web-demo-svc
  labels:
    run: web-demo-svc
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: web-demo
