apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-demo
  name: web-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-demo
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-demo
    spec:
      containers:
      - image: muhammadluthfias/web-demo:latest
        name: web-demo
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-demo
  labels:
    run: web-demo
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: web-demo
